<?php
namespace model\ads\AdManager\LineItemSummary\datasources;
/**
 FILENAME:/var/www/adtopy/model/web/objects/Site/datasources/FullList.php
  CLASS:FullList
*
*
**/

class FullList
{
	 static  $definition=array(
               'ROLE'=>'list',
               'DATAFORMAT'=>'Table',
               'PARAMS'=>array(
                   "id"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"id","TRIGGER_VAR"=>"id"],
                   "name"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"name","TRIGGER_VAR"=>"name","PARAMTYPE"=>"DYNAMIC"],
                   "orderName"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"orderName","TRIGGER_VAR"=>"orderName"],
                   "startDateTime"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"startDateTime","TRIGGER_VAR"=>"startDateTime"],
                   "startDateTimeType"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"startDateTimeType","TRIGGER_VAR"=>"startDateTimeType"],
                   "endDateTime"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"endDateTime","TRIGGER_VAR"=>"endDateTime"],
                   "lineItemType"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"lineItemType","TRIGGER_VAR"=>"lineItemType"],
                   "status"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"status","TRIGGER_VAR"=>"status"],
                   "isArchived"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"isArchived","TRIGGER_VAR"=>"isArchived"],
                   "lastModifiedDateTime"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"lastModifiedDateTime","TRIGGER_VAR"=>"lastModifiedDateTime"],
                   "creationDateTime"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"creationDateTime","TRIGGER_VAR"=>"creationDateTime"],
                   "isSetTopBoxEnabled"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"isSetTopBoxEnabled","TRIGGER_VAR"=>"isSetTopBoxEnabled"],
                   "isMissingCreatives"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"isMissingCreatives","TRIGGER_VAR"=>"isMissingCreatives"],
                   "userConsentEligibility"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"userConsentEligibility","TRIGGER_VAR"=>"userConsentEligibility"],
                   "remoteId"=>["MODEL"=>"/model/ads/AdManager/LineItemSummary","FIELD"=>"remoteId","TRIGGER_VAR"=>"remoteId"]
                     ),
               'IS_ADMIN'=>0,
               'FIELDS'=>array(
                   "orderId"=>["LABEL"=>"orderId","TYPE"=>"Integer"],
                   "id"=>["LABEL"=>"id","TYPE"=>"Integer"],
                   "name"=>["LABEL"=>"name","TYPE"=>"String","MAXLENGTH"=>255],
                   "externalId"=>["LABEL"=>"externalId","TYPE"=>"String","MAXLENGTH"=>255],
                   "orderName"=>["LABEL"=>"orderName","TYPE"=>"String","MAXLENGTH"=>255],
                   "startDateTime"=>["LABEL"=>"startDateTime","TYPE"=>"DateTime"],
                   "startDateTime_timeZoneId"=>["LABEL"=>"startDateTime_timeZoneId","TYPE"=>"String","MAXLENGTH"=>40],
                   "startDateTimeType"=>["LABEL"=>"startDateTimeType","TYPE"=>"Enum","VALUES"=>['USE_START_DATE_TIME','IMMEDIATELY','ONE_HOUR_FROM_NOW','UNKNOWN']],
                   "endDateTime"=>["LABEL"=>"endDateTime","TYPE"=>"DateTime"],
                   "endDateTime_timeZoneId"=>["LABEL"=>"endDateTime_timeZoneId","TYPE"=>"String","MAXLENGTH"=>40],
                   "autoExtensionDays"=>["LABEL"=>"autoExtensionDays","TYPE"=>"Integer"],
                   "unlimitedEndDateTime"=>["LABEL"=>"unlimitedEndDateTime","TYPE"=>"Boolean"],
                   "creativeRotationType"=>["LABEL"=>"creativeRotationType","TYPE"=>"Enum","VALUES"=>['EVEN','OPTIMIZED','MANUAL','SEQUENTIAL']],
                   "deliveryRateType"=>["LABEL"=>"deliveryRateType","TYPE"=>"Enum","VALUES"=>['EVENLY','FRONTLOADED','AS_FAST_AS_POSSIBLE']],
                   "deliveryForecastSource"=>["LABEL"=>"deliveryForecastSource","TYPE"=>"Enum","VALUES"=>['HISTORICAL','FORECASTING','UNKNOWN']],
                   "roadblockingType"=>["LABEL"=>"roadblockingType","TYPE"=>"Enum","VALUES"=>['ONLY_ONE','ONE_OR_MORE','AS_MANY_AS_POSSIBLE','ALL_ROADBLOCK','CREATIVE_SET']],
                   "lineItemType"=>["LABEL"=>"lineItemType","TYPE"=>"Enum","VALUES"=>['SPONSORSHIP','STANDARD','NETWORK','BULK','PRICE_PRIORITY','HOUSE','LEGACY_DFP','CLICK_TRACKING','ADSENSE','AD_EXCHANGE','BUMPER','ADMOB','PREFERRED_DEAL','UNKNOWN']],
                   "priority"=>["LABEL"=>"priority","TYPE"=>"Integer"],
                   "costPerUnit"=>["LABEL"=>"costPerUnit","TYPE"=>"Decimal","NINTEGERS"=>14,"NDECIMALS"=>4],
                   "costPerUnit_currencyCode"=>["LABEL"=>"costPerUnit_currencyCode","TYPE"=>"String","MAXLENGTH"=>4],
                   "valueCostPerUnit"=>["LABEL"=>"valueCostPerUnit","TYPE"=>"Decimal","NINTEGERS"=>14,"NDECIMALS"=>4],
                   "valueCostPerUnit_currencyCode"=>["LABEL"=>"valueCostPerUnit_currencyCode","TYPE"=>"String","MAXLENGTH"=>4],
                   "costType"=>["LABEL"=>"costType","TYPE"=>"Enum","VALUES"=>['CPA','CPC','CPD','CPM','VCPM','UNKNOWN']],
                   "discountType"=>["LABEL"=>"discountType","TYPE"=>"Enum","VALUES"=>['ABSOLUTE_VALUE','PERCENTAGE']],
                   "discount"=>["LABEL"=>"discount","TYPE"=>"Decimal","NINTEGERS"=>12,"NDECIMALS"=>4],
                   "contractedUnitsBought"=>["LABEL"=>"contractedUnitsBought","TYPE"=>"Integer"],
                   "environmentType"=>["LABEL"=>"environmentType","TYPE"=>"Enum","VALUES"=>['BROWSER','VIDEO_PLAYER']],
                   "companionDeliveryOption"=>["LABEL"=>"companionDeliveryOption","TYPE"=>"Enum","VALUES"=>['OPTIONAL','AT_LEAST_ONE','ALL','UNKNOWN']],
                   "allowOverbook"=>["LABEL"=>"allowOverbook","TYPE"=>"Boolean"],
                   "skipInventoryCheck"=>["LABEL"=>"skipInventoryCheck","TYPE"=>"Boolean"],
                   "skipCrossSellingRuleWarningChecks"=>["LABEL"=>"skipCrossSellingRuleWarningChecks","TYPE"=>"Boolean"],
                   "reserveAtCreation"=>["LABEL"=>"reserveAtCreation","TYPE"=>"Boolean"],
                   "budget"=>["LABEL"=>"budget","TYPE"=>"Decimal","NINTEGERS"=>14,"NDECIMALS"=>4],
                   "budget_currencyCode"=>["LABEL"=>"budget_currencyCode","TYPE"=>"String","MAXLENGTH"=>4],
                   "status"=>["LABEL"=>"status","TYPE"=>"Enum","VALUES"=>['DELIVERY_EXTENDED','DELIVERING','READY','PAUSED','INACTIVE','PAUSED_INVENTORY_RELEASED','PENDING_APPROVAL','COMPLETED','DISAPPROVED','DRAFT','CANCELED']],
                   "reservationStatus"=>["LABEL"=>"reservationStatus","TYPE"=>"Enum","VALUES"=>['RESERVED','UNRESERVED']],
                   "isArchived"=>["LABEL"=>"isArchived","TYPE"=>"Boolean"],
                   "webPropertyCode"=>["LABEL"=>"webPropertyCode","TYPE"=>"String","MAXLENGTH"=>255],
                   "disableSameAdvertiserCompetitiveExclusion"=>["LABEL"=>"disableSameAdvertiserCompetitiveExclusion","TYPE"=>"Boolean"],
                   "lastModifiedByApp"=>["LABEL"=>"lastModifiedByApp","TYPE"=>"String","MAXLENGTH"=>255],
                   "notes"=>["LABEL"=>"notes","TYPE"=>"String","MAXLENGTH"=>255],
                   "lastModifiedDateTime"=>["LABEL"=>"lastModifiedDateTime","TYPE"=>"DateTime"],
                   "lastModifiedDateTime_timeZoneId"=>["LABEL"=>"lastModifiedDateTime_timeZoneId","TYPE"=>"String","MAXLENGTH"=>40],
                   "creationDateTime"=>["LABEL"=>"creationDateTime","TYPE"=>"DateTime"],
                   "creationDateTime_timeZoneId"=>["LABEL"=>"creationDateTime_timeZoneId","TYPE"=>"String","MAXLENGTH"=>40],
                   "isPrioritizedPreferredDealsEnabled"=>["LABEL"=>"isPrioritizedPreferredDealsEnabled","TYPE"=>"Boolean"],
                   "adExchangeAuctionOpeningPriority"=>["LABEL"=>"adExchangeAuctionOpeningPriority","TYPE"=>"Integer"],
                   "isSetTopBoxEnabled"=>["LABEL"=>"isSetTopBoxEnabled","TYPE"=>"Boolean"],
                   "isMissingCreatives"=>["LABEL"=>"isMissingCreatives","TYPE"=>"Boolean"],
                   "programmaticCreativeSource"=>["LABEL"=>"programmaticCreativeSource","TYPE"=>"Enum","VALUES"=>['PUBLISHER','ADVERTISER','UNKNOWN']],
                   "videoMaxDuration"=>["LABEL"=>"videoMaxDuration","TYPE"=>"Integer"],
                   "viewabilityProviderCompanyId"=>["LABEL"=>"viewabilityProviderCompanyId","TYPE"=>"Integer"],
                   "userConsentEligibility"=>["LABEL"=>"userConsentEligibility","TYPE"=>"Enum","VALUES"=>['NONE','CONSENTED_OR_NPA','CONSENTED_ONLY','UNKNOWN']],
                   "childContentEligibility"=>["LABEL"=>"childContentEligibility","TYPE"=>"Enum","VALUES"=>['UNKNOWN','DISALLOWED','ALLOWED']],
                   "_remoteTable"=>["LABEL"=>"_remoteTable","TYPE"=>"String","MAXLENGTH"=>40],
                   "remoteId"=>["LABEL"=>"remoteId","TYPE"=>"String"],
                   "_remoteField"=>["LABEL"=>"_remoteField","TYPE"=>"String","MAXLENGTH"=>40]
                     ),
               'PERMISSIONS'=>array(["TYPE"=>"Public"]),
               'SOURCE'=>[
               'STORAGE'=>array(
                     'MYSQL'=>array(
                           'DEFINITION'=>array(
                                 'TABLE'=>'lineitemsummary',
                                 'BASE'=>array(
                                       "*"
                                       ),
                                 'CONDITIONS'=>array(
                                     ["FILTER"=>['F'=>'id','OP'=>'=','V'=>'[%id%]'],'TRIGGER_VAR'=>'id','FILTERREF'=>'id'],
                                     ["FILTER"=>['F'=>'name','OP'=>'=','V'=>'[%name%]'],'TRIGGER_VAR'=>'name','FILTERREF'=>'name'],
                                     ["FILTER"=>['F'=>'orderName','OP'=>'=','V'=>'[%orderName%]'],'TRIGGER_VAR'=>'orderName','FILTERREF'=>'orderName'],
                                     ["FILTER"=>['F'=>'startDateTime','OP'=>'=','V'=>'[%startDateTime%]'],'TRIGGER_VAR'=>'startDateTime','FILTERREF'=>'startDateTime'],
                                     ["FILTER"=>['F'=>'startDateTimeType','OP'=>'=','V'=>'[%startDateTimeType%]'],'TRIGGER_VAR'=>'startDateTimeType','FILTERREF'=>'startDateTimeType'],
                                     ["FILTER"=>['F'=>'endDateTime','OP'=>'=','V'=>'[%endDateTime%]'],'TRIGGER_VAR'=>'endDateTime','FILTERREF'=>'endDateTime'],
                                     ["FILTER"=>['F'=>'lineItemType','OP'=>'=','V'=>'[%lineItemType%]'],'TRIGGER_VAR'=>'lineItemType','FILTERREF'=>'lineItemType'],
                                     ["FILTER"=>['F'=>'status','OP'=>'=','V'=>'[%status%]'],'TRIGGER_VAR'=>'status','FILTERREF'=>'status'],
                                     ["FILTER"=>['F'=>'isArchived','OP'=>'=','V'=>'[%isArchived%]'],'TRIGGER_VAR'=>'isArchived','FILTERREF'=>'isArchived'],
                                     ["FILTER"=>['F'=>'lastModifiedDateTime','OP'=>'=','V'=>'[%lastModifiedDateTime%]'],'TRIGGER_VAR'=>'lastModifiedDateTime','FILTERREF'=>'lastModifiedDateTime'],
                                     ["FILTER"=>['F'=>'creationDateTime','OP'=>'=','V'=>'[%creationDateTime%]'],'TRIGGER_VAR'=>'creationDateTime','FILTERREF'=>'creationDateTime'],
                                     ["FILTER"=>['F'=>'isSetTopBoxEnabled','OP'=>'=','V'=>'[%isSetTopBoxEnabled%]'],'TRIGGER_VAR'=>'isSetTopBoxEnabled','FILTERREF'=>'isSetTopBoxEnabled'],
                                     ["FILTER"=>['F'=>'isMissingCreatives','OP'=>'=','V'=>'[%isMissingCreatives%]'],'TRIGGER_VAR'=>'isMissingCreatives','FILTERREF'=>'isMissingCreatives'],
                                     ["FILTER"=>['F'=>'userConsentEligibility','OP'=>'=','V'=>'[%userConsentEligibility%]'],'TRIGGER_VAR'=>'userConsentEligibility','FILTERREF'=>'userConsentEligibility'],
                                     ["FILTER"=>['F'=>'remoteId','OP'=>'=','V'=>'[%remoteId%]'],'TRIGGER_VAR'=>'remoteId','FILTERREF'=>'remoteId'],
                                       )
                                 )
                           )
                     )
                   ]
               );
}
