[*PAGE/HTMLPAGE]
    [_TITLE]El titulo[#]
    [_CONTENT]
        [*:LAYOUTS/LAYOUT_3]
            [_:LEFTSIDEBAR]
                [*::/model/web/objects/Site/html/views/SitesMenu][#]
            [#]
            [_:CONTENT]
                [*::/model/web/objects/Page/html/views/FullList][#]
            [#]
            [_:RIGHTSIDEBAR]

            [#]
        [#]
    [#]
[#]
