[*PAGE/WORKER]
    [_TITLE]Workers: Backend - SmartClip v.1.0 beta[#]

    [_CONTENT]
        [*:BEHAVIOR/CARD]
            [_:TITLE]Detalle del trabajo[#]
            [_:CONTENT][*::WorkerFullList][#][#]
        [#]        
    [#]   
[#]