<?php

namespace model\Ads\objects\AdManager;
include_once(LIBPATH . "/data/DataTransform.php");

/**
 * Created by PhpStorm.
 * User: Usuario
 * Date: 02/09/2016
 * Time: 13:30
 */
class Definition extends \lib\model\BaseModelDefinition
{


    static $definition = array(

        "FIELDS" => array(
            "DATE" =>
                array(
                    'groupable' => true,
                    'filtrable' => true,
                    'fieldgroup' => 'DATE_TIME',
                    'description' => 'Breaks down reporting data by date in the network time zone. Can be used to
                    filter by date using ISO 8601\'s format \'YYYY-MM-DD\'".
                ',
                    "TYPE" => 'Date',
                ),
            "HOUR" =>
                array(
                    'groupable' => true,
                    'filtrable' => true,
                    "TYPE" => 'Integer',
                    'fieldgroup' => 'DATE_TIME',
                    'description' => 'Breaks down reporting data by hour of the day in the network time zone. Can
                    be used to filter by hour of the day (from 0 to 23).
                '),
            "AD_UNIT_ID" =>
                array(
                    'groupable' => true,
                    'filtrable' => true,
                    "TYPE" => 'String',
                    'fieldgroup' => 'AD_UNIT',
                    'description' => 'Breaks down reporting data by <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#id">AdUnit.id</a>. Can be used to filter by
                    <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#id">AdUnit.id</a>. <a class="codelink" href="#AD_UNIT_NAME">AD_UNIT_NAME</a>, i.e. <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#name">AdUnit.name</a>, is
                    automatically included as a dimension in the report.',
                ),
            "AD_UNIT_NAME" =>
                array(
                    'groupable' => true,
                    'filtrable' => true,
                    "TYPE" => '\model\Ads\objects\AdManager\types\AdUnitName',
                    'fieldgroup' => 'AD_UNIT',
                    'description' => 'Breaks down reporting data by ad unit. <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#name">AdUnit.name</a> and
                    <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#id">AdUnit.id</a> are automatically included as columns in the report. Can
                    be used to filter by <a class="codelink" href="https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.AdUnit.html#name">AdUnit.name</a>.',
                ),
            "AD_SERVER_IMPRESSIONS" =>
                array(
                    'description' => 'The number of impressions delivered by the ad server.',
                    'fieldgroup' => 'AD_SERVER',
                    "TYPE" => 'Integer',
                ),
            "AD_SERVER_CPM_AND_CPC_REVENUE" =>
                array(
                    'fieldgroup' => 'AD_SERVER',
                    'description' => 'The CPM and CPC revenue earned, calculated in publisher currency,
                    for the ads delivered by the ad server.',
                    "TYPE" => 'Decimal',
                    "NINTEGERS"=>6,
                    "NDECIMALS"=>6
                ),
            "TOTAL_LINE_ITEM_LEVEL_CTR" =>
                array(
                    "TYPE" => 'Percentage',
                    'fieldgroup' => 'TOTAL/LINE_ITEM_LEVEL',
                    'description' => 'The ratio of total clicks on ads delivered by the ad servers to the total number
                    of impressions delivered for an ad including line item-level dynamic allocation.',
                ),
            "AD_EXCHANGE_IMPRESSIONS" =>
                array(
                    "TYPE" => 'Integer',
                    'description' => 'Ad impressions (legacy) on mapped Ad Exchange properties. In the case of text ads, you may have one matched request which yields more than one ad impression, since multiple text ads can serve in place of one display ad.',
                ),
            "AD_EXCHANGE_ESTIMATED_REVENUE" =>
                array(
                    "TYPE" => 'Decimal',
                    "NINTEGERS"=>6,
                    "NDECIMALS"=>6,
                    'description' => 'The estimated net revenue generated by mapped Ad Exchange properties.',
                ),
            "IO"=>array(
                "TYPE"=>"String"
            )
        )


    );
}
