<?php
/**
 * Created by PhpStorm.
 * User: JoseMaria
 * Date: 05/12/2017
 * Time: 0:22
 */

namespace sites\editor\pages\Login;


class LoginPage extends \model\web\Page
{
    function initializePage($params)
    {
        // TODO: Implement initializePage() method.
        $user=\Registry::getService("user");
        if($user->isLogged())
        {
            $this->onFormSuccess(null);
        }
    }
    function onFormSuccess($form)
    {
        $response=\Registry::$registry["response"];
        $response->setBuilder(\lib\Response::redirect($this->generateUrl("index")));
    }
    function onFormError($form)
    {
        parent::onFormError($form); // TODO: Change the autogenerated stub
    }
}