<?php
namespace model\web\Page\datasources;
/**
 FILENAME:/var/www/adtopy/model/web/objects/Page/datasources/AdminFullList.php
  CLASS:AdminFullList
*
*
**/

class AdminFullList
{
	 static  $definition=array(
               'ROLE'=>'list',
               'DATAFORMAT'=>'Table',
               'PARAMS'=>array(
                     'id_page'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'id_page',
                           'TRIGGER_VAR'=>'id_page'
                           ),
                     'tag'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'tag',
                           'TRIGGER_VAR'=>'tag'
                           ),
                     'name'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'name',
                           'TRIGGER_VAR'=>'name'
                           ),
                     'date_add'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'date_add',
                           'TRIGGER_VAR'=>'date_add'
                           ),
                     'date_modified'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'date_modified',
                           'TRIGGER_VAR'=>'date_modified'
                           ),
                     'id_type'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'id_type',
                           'TRIGGER_VAR'=>'id_type'
                           ),
                     'isPrivate'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'isPrivate',
                           'TRIGGER_VAR'=>'isPrivate'
                           ),
                     'path'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'path',
                           'TRIGGER_VAR'=>'path'
                           ),
                     'title'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'title',
                           'TRIGGER_VAR'=>'title'
                           ),
                     'tags'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'tags',
                           'TRIGGER_VAR'=>'tags'
                           ),
                     'description'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'description',
                           'TRIGGER_VAR'=>'description'
                           )
                     ),
               'IS_ADMIN'=>1,
               'FIELDS'=>array(
                     'id_page'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'id_page'
                           ),
                     'tag'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'tag'
                           ),
                     'name'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'name'
                           ),
                     'date_add'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'date_add'
                           ),
                     'date_modified'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'date_modified'
                           ),
                     'id_type'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'id_type'
                           ),
                     'isPrivate'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'isPrivate'
                           ),
                     'path'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'path'
                           ),
                     'title'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'title'
                           ),
                     'tags'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'tags'
                           ),
                     'description'=>array(
                           'MODEL'=>'\model\web\Page',
                           'FIELD'=>'description'
                           )
                     ),
               'PERMISSIONS'=>array(
                     array(
                           'MODEL'=>'Page',
                           'PERMISSION'=>'adminList'
                           )
                     ),
         'SOURCE'=>[
               'STORAGE'=>array(
                     'MYSQL'=>array(
                           'DEFINITION'=>array(
                                 'TABLE'=>'page',
                                 'BASE'=>array(
                                       'id_page',
                                       'tag',
                                       'name',
                                       'date_add',
                                       'date_modified',
                                       'id_type',
                                       'isPrivate',
                                       'path',
                                       'title',
                                       'tags',
                                       'description'
                                       ),
                                 'CONDITIONS'=>array(
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'id_page',
                                                   'OP'=>'=',
                                                   'V'=>'[%id_page%]'
                                                   ),
                                             'TRIGGER_VAR'=>'id_page',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'id_page'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'tag',
                                                   'OP'=>'=',
                                                   'V'=>'[%tag%]'
                                                   ),
                                             'TRIGGER_VAR'=>'tag',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'tag'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'name',
                                                   'OP'=>'=',
                                                   'V'=>'[%name%]'
                                                   ),
                                             'TRIGGER_VAR'=>'name',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'name'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'date_add',
                                                   'OP'=>'=',
                                                   'V'=>'[%date_add%]'
                                                   ),
                                             'TRIGGER_VAR'=>'date_add',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'date_add'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'date_modified',
                                                   'OP'=>'=',
                                                   'V'=>'[%date_modified%]'
                                                   ),
                                             'TRIGGER_VAR'=>'date_modified',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'date_modified'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'id_type',
                                                   'OP'=>'=',
                                                   'V'=>'[%id_type%]'
                                                   ),
                                             'TRIGGER_VAR'=>'id_type',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'id_type'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'isPrivate',
                                                   'OP'=>'=',
                                                   'V'=>'[%isPrivate%]'
                                                   ),
                                             'TRIGGER_VAR'=>'isPrivate',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'isPrivate'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'path',
                                                   'OP'=>'=',
                                                   'V'=>'[%path%]'
                                                   ),
                                             'TRIGGER_VAR'=>'path',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'path'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'title',
                                                   'OP'=>'=',
                                                   'V'=>'[%title%]'
                                                   ),
                                             'TRIGGER_VAR'=>'title',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'title'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'tags',
                                                   'OP'=>'=',
                                                   'V'=>'[%tags%]'
                                                   ),
                                             'TRIGGER_VAR'=>'tags',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'tags'
                                             ),
                                       array(
                                             'FILTER'=>array(
                                                   'F'=>'description',
                                                   'OP'=>'=',
                                                   'V'=>'[%description%]'
                                                   ),
                                             'TRIGGER_VAR'=>'description',
                                             'DISABLE_IF'=>'0',
                                             'FILTERREF'=>'description'
                                             )
                                       )
                                 )
                           )
                     )
             ]
               );
}
?>
